Учебный проект: холст
htmlacademy-javascript/1106215-code-and-magick-21 pull request #2
Opened 2020-09-19 14:44 UTC by whoisdaria

2020-09-19 17:58 UTC, balesniy requested changes

2020-09-19 17:58 UTC, balesniy commented on js/stat.js
> +var maxBarWidth = 150;
константы нужно оформить в SNAKE_CASE

2020-09-19 17:58 UTC, balesniy commented on js/stat.js
> +var getMaxElement = function(arr) {
сокращения в названиях запрещены, для элементов массива можно использовать elements или items

2020-09-19 17:58 UTC, balesniy commented on js/stat.js
> +      ctx.fillStyle = 'rgb(255, 0, 0)';
тут будет уместно использовать тернарный оператор, см https://up.htmlacademy.ru/javascript/21/criteries#d17

2020-09-19 17:58 UTC, balesniy commented on js/stat.js
> +      ctx.fillStyle = 'hsl(240, ' + 10 * i + '% , 50%)';
"насыщенность задаётся случайным образом" - нам нужна функция получения случайного цвета

2020-09-19 17:58 UTC, balesniy commented on js/stat.js
> +    ctx.fillText(Math.round(times[i]), CLOUD_X + GAP + (BAR_WIDTH + GAP) * i, 90 + (maxBarWidth - (maxBarWidth * times[i]) / maxTime), BAR_WIDTH, (maxBarWidth * times[i]) / maxTime)
повторяющиеся значения можно вынести из выражений, например `CLOUD_X + GAP + (BAR_WIDTH + GAP) * i`

2020-09-21 10:40 UTC, whoisdaria commented on js/stat.js
> +      ctx.fillStyle = 'hsl(240, ' + 10 * i + '% , 50%)';
сделала рандомный процент насыщенности, это норм?

2020-09-21 10:59 UTC, balesniy commented on js/stat.js
> +      ctx.fillStyle = 'hsl(240, ' + 10 * i + '% , 50%)';
да, именно такое и просят 👍  получение рандомного значения имеет смысл вынести в функцию, она нам еще пригодится

2020-09-21 14:59 UTC, whoisdaria commented on js/stat.js
> +      ctx.fillStyle = 'hsl(240, ' + 10 * i + '% , 50%)';
вынесла

2020-09-21 16:01 UTC, balesniy requested changes

2020-09-21 16:01 UTC, balesniy commented on js/stat.js
> +    names[i] === 'Вы' ? ctx.fillStyle = 'rgb(255, 0, 0)' : ctx.fillStyle = 'hsl(240, ' + saturation + '% , 50%)';
тернарный оператор нужен для вычисления значения, которое мы дальше используем, критерий запрещает нам использовать присваивание как часть выражения, тут получится что то вроде `ctx.fillStyle = names[i] === 'Вы' ? красный: синий`

2020-09-22 17:23 UTC, balesniy commented
возможно не пришли замечания к последнему комиту, проверь еще раз пожалуйста, про тернарный и константы

2020-09-23 15:47 UTC, merged