Учебный проект: нас орда
htmlacademy-javascript/1106215-code-and-magick-21 pull request #3
Opened 2020-10-03 13:34 UTC by whoisdaria

2020-10-03 14:56 UTC, balesniy requested changes

2020-10-03 19:32 UTC, balesniy requested changes

2020-10-03 19:32 UTC, balesniy commented on js/setup.js
> +var FIRST_NAMES = ['Иван', 'Хуан Себастьян', 'Мария', 'Кристоф', 'Виктор', 'Юлия', 'Люпита', 'Вашингтон'];
константы нужно перенести в начало модуля

2020-10-03 19:32 UTC, balesniy commented on js/setup.js
> +var getNumber = (array) => getRandomNumber(0, array.length-1);
в названии массивов нас просят использовать множественное число, а название функции должно отражать ее действие, тут будет что вроде getRandomIndex

2020-10-03 19:32 UTC, balesniy commented on js/setup.js
> +for (let i = 0; i < 4; i++) {
let и var не стоит перемешивать, если мы используем es6 синтаксис, то давай тогда убирать все var

2020-10-03 19:32 UTC, balesniy commented on js/setup.js
> +  var wizard = new Object();
мы пока про конструкторы не знаем, можно просто в литералах объявить `var wizard = {};`

2020-10-03 19:32 UTC, balesniy commented on js/setup.js
> +console.log(wizards)
отладочный код нужно убрать

2020-10-03 19:32 UTC, balesniy commented on js/setup.js
> +}
код генерации данных нужно оформить в функцию, которая примет параметром кол-во объектов и вернет массив

2020-10-03 19:32 UTC, balesniy commented on js/setup.js
> +var fragment = document.createDocumentFragment();
код отрисовки данных нужно оформить в функцию, которая примет параметром массив с данными

2020-10-04 13:07 UTC, balesniy requested changes

2020-10-04 13:07 UTC, balesniy commented on js/setup.js
> +var elementsQuantity = 4;
константу нужно назвать в SNAKE_CASE и вынести в начало модуля

2020-10-04 13:07 UTC, balesniy commented on js/setup.js
> +var getRandomIndex = (array) => getRandomNumber(0, array.length-1);
массивы нужно назвать во множественном числе, array не подходит, нам нужно или дать осмысленное название, или можно что то абстрактное типа data items elements

2020-10-04 13:07 UTC, balesniy commented on js/setup.js
> +  return wizards;
если функция возвращает значение, то имеет смысл создавать массив внутри функции, это сделает функцию более универсальной, позволит нам создавать разные наборы данных. или убрать return, сейчас результат вызова функции не используется

2020-10-04 13:07 UTC, balesniy commented on js/setup.js
> +var LAST_NAMES = ['да Марья',  'Верон',  'Мирабелла','Вальц', 'Онопко', 'Топольницкая', 'Нионго', 'Ирвинг'];
тут и дальше линтер жалуется "4:30   error    Multiple spaces found before ''Верон''" - нужно поправить по стилю

2020-10-04 16:53 UTC, balesniy commented on js/setup.js
> +var createData = (ELEMENTS_QUANTITY) => {
капсом мы обозначаем только константы, параметры функции нужны для передачи разных значений, они константами быть не могут, тут нужен camelCase

2020-10-04 16:59 UTC, whoisdaria commented on js/setup.js
> +var createData = (ELEMENTS_QUANTITY) => {
поправила

2020-10-04 17:03 UTC, balesniy commented on js/setup.js
> +var createData = (ELEMENTS_QUANTITY) => {
отлично, теперь еще линтер остался

2020-10-04 17:38 UTC, merged